name: 'Add brotli encoding understanding to Python used by awscli'
description: >-
  Inject brotli encoding file extension into Python's mimetypes db

runs:
  using: "composite"
  steps:
    - name: Add brotli encoding to Python interpreter used by awscli
      shell: bash
      run: |
        set -eu
        set -o pipefail

        version_string="$(aws --version)"
        if [[ "$version_string" =~ .*ython/3\.[89].*\ exe/.* ]]; then
            echo "Running with Python 3.9 compiled dist; no need to install"
            exit 0
        elif [[ "$version_string" =~ .*\ ython/[23]\.[0-7]\..*\ exe/.* ]]; then
            echo "Running compiled aws cli dist without brotli; unable to proceed"
            exit 1
        fi

        PYTHON="$(head -n1 "$(readlink -f "$(which aws)")" | sed 's/^#! *//')"
        echo "awscli is installed with $PYTHON as the interpreter"

        hasbrotli() {
            # Return 1 (bash error code) if .br not in encodings
            "$PYTHON" -c 'import mimetypes; import sys; sys.exit(".br" not in mimetypes.encodings_map)'
        }

        if hasbrotli; then
            echo "$PYTHON already knows about brotli as a mime encoding"
            exit 0
        fi

        PREFIX="$("$PYTHON" -c 'import sys; print(sys.prefix)')"
        VERSION="$("$PYTHON" -c 'import sys; print("{}.{}".format(*sys.version_info[:2]))')"
        PYTHONLIB="${PREFIX}/lib/python${VERSION}"

        echo "python interpreter is version ${VERSION} is located in $PREFIX"
        echo "python libdir located at $PYTHONLIB"

        cat <<EOF > sitecustomize.py
        import mimetypes
        mimetypes.encodings_map['.br'] = 'br'
        EOF

        echo "Installing brotli encoding mimetype"
        sudo install -m 644 -o root -g root sitecustomize.py "${PYTHONLIB}/sitecustomize.py"
        rm sitecustomize.py

        hasbrotli
